version: "3.8"
services:
  garden_web_server:
    build:
      context: .
      dockerfile: ./dockerfiles/garden_web_server/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - garden_manager

  garden_manager:
    build:
      context: .
      dockerfile: ./dockerfiles/garden_manager/Dockerfile
    depends_on:
      db:
        condition: service_healthy

  mosquitto:
    build:
      context: .
      dockerfile: ./dockerfiles/mosquitto/Dockerfile
    ports:
      - "1883:1883"

  db:
    build:
      context: .
      dockerfile: ./dockerfiles/database/Dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: garden_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5